In [ ]:
!pip install PySUS

Collecting PySUS
  Downloading pysus-1.0.1-py3-none-any.whl.metadata (1.3 kB)
Collecting Unidecode<2.0.0,>=1.3.6 (from PySUS)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Collecting aioftp<0.22.0,>=0.21.4 (from PySUS)
  Downloading aioftp-0.21.4-py3-none-any.whl.metadata (6.1 kB)
Collecting bigtree<0.13.0,>=0.12.2 (from PySUS)
  Downloading bigtree-0.12.5-py3-none-any.whl.metadata (28 kB)
Collecting dateparser<2.0.0,>=1.1.8 (from PySUS)
  Downloading dateparser-1.3.0-py3-none-any.whl.metadata (30 kB)
Collecting dbfread==2.0.7 (from PySUS)
  Downloading dbfread-2.0.7-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting elasticsearch==7.16.2 (from elasticsearch[preprocessing]==7.16.2->PySUS)
  Downloading elasticsearch-7.16.2-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting fastparquet<=2024.11.0,>=2023.10.1 (from PySUS)
  Downloading fastparquet-2024.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from PySUS) (4.15.0)
Collecting loguru<0.7.0,>=0.6.0 (from PySUS)
  Downloading loguru-0.6.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: numpy<3,>1 in /usr/local/lib/python3.12/dist-packages (from PySUS) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from PySUS) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.12/dist-packages (from PySUS) (18.1.0)
Collecting pycparser==2.21 (from PySUS)
  Downloading pycparser-2.21-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting pyreaddbc>=1.1.0 (from PySUS)
  Downloading pyreaddbc-1.2.0.tar.gz (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 4.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-dateutil==2.8.2 (from PySUS)
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl.metadata (8.2 kB)
Collecting tqdm==4.64.0 (from PySUS)
  Downloading tqdm-4.64.0-py2.py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from PySUS) (4.15.0)
Collecting urwid<3.0.0,>=2.1.2 (from PySUS)
  Downloading urwid-2.6.16-py3-none-any.whl.metadata (11 kB)
Collecting wget<4.0,>=3.2 (from PySUS)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Collecting urllib3<2,>=1.21.1 (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->PySUS)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->PySUS) (2026.2.25)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil==2.8.2->PySUS) (1.17.0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->PySUS) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->PySUS) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->PySUS) (5.3.1)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->PySUS) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->PySUS) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->PySUS) (26.0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.2->PySUS) (2025.3)
Collecting cffi<2,>=1.15.1 (from pyreaddbc>=1.1.0->PySUS)
  Downloading cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.12/dist-packages (from pyreaddbc>=1.1.0->PySUS) (6.0.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from urwid<3.0.0,>=2.1.2->PySUS) (0.6.0)
Downloading pysus-1.0.1-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 53.6 MB/s eta 0:00:00
Downloading dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Downloading elasticsearch-7.16.2-py2.py3-none-any.whl (385 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 21.9 MB/s eta 0:00:00
Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 8.7 MB/s eta 0:00:00
Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 14.6 MB/s eta 0:00:00
Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 5.3 MB/s eta 0:00:00
Downloading aioftp-0.21.4-py3-none-any.whl (37 kB)
Downloading bigtree-0.12.5-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 4.0 MB/s eta 0:00:00
Downloading dateparser-1.3.0-py3-none-any.whl (318 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.7/318.7 kB 20.3 MB/s eta 0:00:00
Downloading fastparquet-2024.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 64.2 MB/s eta 0:00:00
Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 3.7 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 17.3 MB/s eta 0:00:00
Downloading urwid-2.6.16-py3-none-any.whl (297 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.2/297.2 kB 21.8 MB/s eta 0:00:00
Downloading cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (479 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 479.4/479.4 kB 25.0 MB/s eta 0:00:00
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 10.0 MB/s eta 0:00:00
Building wheels for collected packages: pyreaddbc, wget
  Building wheel for pyreaddbc (pyproject.toml) ... done
  Created wheel for pyreaddbc: filename=pyreaddbc-1.2.0-cp312-cp312-manylinux_2_35_x86_64.whl size=90781 sha256=9086a356f35108b6bdf179b4b1d499fbdcb5a4d6435433be52fa86097dee1b49
  Stored in directory: /root/.cache/pip/wheels/74/bb/66/8fdae279ef4c91b7a727a88c5b2412e0f3241ff489538f87b7
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=1ad22964deb9922a0605187676eb9cf3e270e36ba744b8cbebaea4c491c7ecd1
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built pyreaddbc wget
Installing collected packages: wget, dbfread, urwid, urllib3, Unidecode, tqdm, python-dateutil, pycparser, loguru, bigtree, aioftp, elasticsearch, dateparser, cffi, pyreaddbc, fastparquet, PySUS
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.3
    Uninstalling tqdm-4.67.3:
      Successfully uninstalled tqdm-4.67.3
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: pycparser
    Found existing installation: pycparser 3.0
    Uninstalling pycparser-3.0:
      Successfully uninstalled pycparser-3.0
  Attempting uninstall: cffi
    Found existing installation: cffi 2.0.0
    Uninstalling cffi-2.0.0:
      Successfully uninstalled cffi-2.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 1.27.1 requires python-dateutil<3.0.0,>=2.9.0.post0, but you have python-dateutil 2.8.2 which is incompatible.
dataproc-spark-connect 1.0.2 requires tqdm>=4.67, but you have tqdm 4.64.0 which is incompatible.
datasets 4.0.0 requires tqdm>=4.66.3, but you have tqdm 4.64.0 which is incompatible.
blobfile 3.2.0 requires urllib3>=2, but you have urllib3 1.26.20 which is incompatible.
tobler 0.13.0 requires tqdm>=4.67, but you have tqdm 4.64.0 which is incompatible.
momepy 0.11.0 requires tqdm>=4.65, but you have tqdm 4.64.0 which is incompatible.
dopamine-rl 4.1.2 requires tqdm>=4.64.1, but you have tqdm 4.64.0 which is incompatible.
holidays 0.93 requires python-dateutil<3,>=2.9.0.post0, but you have python-dateutil 2.8.2 which is incompatible.
spopt 0.7.0 requires tqdm>=4.66.0, but you have tqdm 4.64.0 which is incompatible.
pygit2 1.19.1 requires cffi>=2.0, but you have cffi 1.17.1 which is incompatible.
Successfully installed PySUS-1.0.1 Unidecode-1.4.0 aioftp-0.21.4 bigtree-0.12.5 cffi-1.17.1 dateparser-1.3.0 dbfread-2.0.7 elasticsearch-7.16.2 fastparquet-2024.11.0 loguru-0.6.0 pycparser-2.21 pyreaddbc-1.2.0 python-dateutil-2.8.2 tqdm-4.64.0 urllib3-1.26.20 urwid-2.6.16 wget-3.2

In [ ]:
import pandas as pd
from pysus.online_data import IBGE
from pysus.ftp.databases.sim import SIM
from pysus.ftp.databases.sinan import SINAN

In [ ]:
# 1. Inicializa o SINAN
sinan = SINAN().load()

# 2. Busca os arquivos de Dengue ('DENG') para um ano recente (ex: 2022 ou 2023)
# Baixar múltiplos anos pode demorar um pouco
arquivos_dengue = sinan.get_files('DENG', 2022)

# 3. Faz o download e converte para DataFrame Pandas
df_dengue = sinan.download(arquivos_dengue).to_dataframe()

# 4. Transforma a coluna de Município em número para facilitar o filtro
df_dengue['ID_MUNICIP'] = pd.to_numeric(df_dengue['ID_MUNICIP'], errors='coerce')

# 5. FILTRA PARA CAMPINAS (Código IBGE do município: 350950)
df_campinas = df_dengue[df_dengue['ID_MUNICIP'] == 350950].copy()

# 6. Converte as colunas de Data
df_campinas['DT_NOTIFIC'] = pd.to_datetime(df_campinas['DT_NOTIFIC'], errors='coerce')
df_campinas['DT_SIN_PRI'] = pd.to_datetime(df_campinas['DT_SIN_PRI'], errors='coerce')

# 7. Visualiza os dados principais para o SIEST
colunas_interesse = ['DT_NOTIFIC', 'DT_SIN_PRI', 'ID_UNIDADE', 'CLASSI_FIN']
print(f"Total de casos em Campinas no ano selecionado: {len(df_campinas)}")
df_campinas[colunas_interesse].head()

DENGBR22.parquet: 100%|██████████| 2.29M/2.29M [03:54<00:00, 9.75kB/s]

Total de casos em Campinas no ano selecionado: 12446

      DT_NOTIFIC DT_SIN_PRI ID_UNIDADE CLASSI_FIN
9010  2022-09-05 2022-09-02    9617930         8
27319 2022-04-11 2022-04-07    2079666         10
63068 2022-03-10 2022-03-03    2078376         10
63069 2022-03-09 2022-03-02    2078376         10
84769 2022-06-23 2022-06-19    6053858         8

In [ ]:
# vasculhar as colunas para encontrar a que se refere a Bairro
colunas_bairro = [col for col in df_campinas.columns if 'MUN' in col]
print(f"Possíveis colunas para MUNICIPIO: {colunas_bairro}")

Possíveis colunas para MUNICIPIO: ['ID_MUNICIP', 'AUTO_IMUNE', 'IMUNOH_N', 'MUNICIPIO', 'COMUNINF']

In [ ]:
print(list(df_campinas.columns))

['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT', 'ID_MUNICIP', 'ID_REGIONA', 'ID_UNIDADE', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC', 'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N', 'FEBRE', 'MIALGIA', 'CEFALEIA', 'EXANTEMA', 'VOMITO', 'NAUSEA', 'DOR_COSTAS', 'CONJUNTVIT', 'ARTRITE', 'ARTRALGIA', 'PETEQUIA_N', 'LEUCOPENIA', 'LACO', 'DOR_RETRO', 'DIABETES', 'HEMATOLOG', 'HEPATOPAT', 'RENAL', 'HIPERTENSA', 'ACIDO_PEPT', 'AUTO_IMUNE', 'DT_CHIK_S1', 'DT_CHIK_S2', 'DT_PRNT', 'RES_CHIKS1', 'RES_CHIKS2', 'RESUL_PRNT', 'DT_SORO', 'RESUL_SORO', 'DT_NS1', 'RESUL_NS1', 'DT_VIRAL', 'RESUL_VI_N', 'DT_PCR', 'RESUL_PCR_', 'SOROTIPO', 'HISTOPA_N', 'IMUNOH_N', 'HOSPITALIZ', 'DT_INTERNA', 'UF', 'MUNICIPIO', 'TPAUTOCTO', 'COUFINF', 'COPAISINF', 'COMUNINF', 'CLASSI_FIN', 'CRITERIO', 'DOENCA_TRA', 'CLINC_CHIK', 'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'ALRM_HIPOT', 'ALRM_PLAQ', 'ALRM_VOM', 'ALRM_SANG', 'ALRM_HEMAT', 'ALRM_ABDOM', 'ALRM_LETAR', 'ALRM_HEPAT', 'ALRM_LIQ', 'DT_ALRM', 'GRAV_PULSO', 'GRAV_CONV', 'GRAV_ENCH', 'GRAV_INSUF', 'GRAV_TAQUI', 'GRAV_EXTRE', 'GRAV_HIPOT', 'GRAV_HEMAT', 'GRAV_MELEN', 'GRAV_METRO', 'GRAV_SANG', 'GRAV_AST', 'GRAV_MIOC', 'GRAV_CONSC', 'GRAV_ORGAO', 'DT_GRAV', 'MANI_HEMOR', 'EPISTAXE', 'GENGIVO', 'METRO', 'PETEQUIAS', 'HEMATURA', 'SANGRAM', 'LACO_N', 'PLASMATICO', 'EVIDENCIA', 'PLAQ_MENOR', 'CON_FHD', 'COMPLICA', 'TP_SISTEMA', 'NDUPLIC_N', 'DT_DIGITA', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W']

In [ ]:
colunas_interesse = ['DT_NOTIFIC', 'DT_SIN_PRI', 'ID_UNIDADE', 'CLASSI_FIN']

df_campinas_limpo = df_campinas[colunas_interesse].copy()
df_campinas_limpo

        DT_NOTIFIC DT_SIN_PRI ID_UNIDADE CLASSI_FIN
9010    2022-09-05 2022-09-02    9617930         8
27319   2022-04-11 2022-04-07    2079666         10
63068   2022-03-10 2022-03-03    2078376         10
63069   2022-03-09 2022-03-02    2078376         10
84769   2022-06-23 2022-06-19    6053858         8
...            ...        ...        ...        ...
1402703 2022-04-03 2022-03-17    3846296         8
1402710 2022-03-31 2022-03-25    2079666         10
1402748 2022-04-18 2022-04-13    2079666         10
1402784 2022-12-01 2022-11-22    2036398         8
1403854 2022-05-05 2022-04-26    2079798         11

[12446 rows x 4 columns]

In [ ]:
unidades_campinas = df_campinas_limpo['ID_UNIDADE'].dropna().unique()
print(f"Total de unidades de saúde para mapear: {len(unidades_campinas)}")

Total de unidades de saúde para mapear: 126

In [ ]:
#import pandas as pd
import os
#from pysus.ftp.databases.sinan import SINAN

# ---------------------------------------------------------
# 1. CONFIGURAÇÕES GERAIS DO PROJETO SIEST
# ---------------------------------------------------------

# Inicializa o módulo do SINAN
sinan = SINAN().load()

# Código IBGE de Campinas
IBGE_CAMPINAS = 350950

# Janela temporal: 2014 a 2026 (o range no Python vai até o número anterior ao limite)
anos_analise = range(2014, 2027)

# Lista de agravos (Doenças) baseada no ODS 13 e integração epidemiológica
# DENG (Dengue), CHIK (Chikungunya), ZIKA (Zika), LEPT (Leptospirose), HEPA (Hepatites Virais)
doencas = ['DENG', 'CHIK', 'ZIKA', 'LEPT', 'HEPA']

# Lista expandida das colunas de interesse (O "Dicionário" do SIEST)
colunas_alvo = [
    'ID_MUNICIP',  # Para garantir o filtro espacial
    'ID_UNIDADE',  # CNES: O Nó do nosso Grafo
    'DT_NOTIFIC',  # Data da notificação
    'DT_SIN_PRI',  # Data dos primeiros sintomas (Crucial para clima)
    'NU_IDADE_N',  # Idade do paciente
    'CS_SEXO',     # Sexo
    'HOSPITALIZ',  # Indicador de sobrecarga hospitalar (1-Sim, 2-Não)
    'CLASSI_FIN',  # Classificação final do caso
    'EVOLUCAO',    # Evolução (Cura, Óbito, etc)
    'CRITERIO'     # Critério de confirmação
]

# Cria um diretório para organizar os dados limpos
os.makedirs('dados_siest_parquet', exist_ok=True)

# ---------------------------------------------------------
# 2. MOTOR DE EXTRAÇÃO E TRANSFORMAÇÃO (ETL)
# ---------------------------------------------------------

print("Iniciando o Pipeline de ETL do SIEST...")

# Loop Duplo: Para cada doença, varre todos os anos
for doenca in doencas:
    print(f"\\n--- Extraindo dados para: {doenca} ---")

    for ano in anos_analise:
        try:
            # Extração dos arquivos do FTP do DataSUS
            arquivos = sinan.get_files(doenca, ano)

            # Se não houver arquivos para a doença/ano, pula para o próximo
            if not arquivos:
                print(f"[{ano}] Sem arquivos no servidor para {doenca}.")
                continue

            df_bruto = sinan.download(arquivos).to_dataframe()

            # Transformação 1: Converter ID_MUNICIP para numérico para aplicar o filtro
            df_bruto['ID_MUNICIP'] = pd.to_numeric(df_bruto['ID_MUNICIP'], errors='coerce')

            # Transformação 2: Filtro Espacial (Apenas Campinas)
            df_campinas = df_bruto[df_bruto['ID_MUNICIP'] == IBGE_CAMPINAS].copy()

            # Se não houver casos em Campinas neste ano, pula
            if df_campinas.empty:
                print(f"[{ano}] 0 casos registrados em Campinas para {doenca}.")
                continue

            # Transformação 3: Interseção de Colunas (Evita o KeyError)
            # Pega apenas as colunas da nossa lista que realmente existem no arquivo atual
            colunas_existentes = df_campinas.columns.intersection(colunas_alvo)
            df_campinas = df_campinas[colunas_existentes]

            # Carga (Load): Salvar em Parquet com compressão
            nome_arquivo = f"dados_siest_parquet/{doenca}_campinas_{ano}.parquet"
            df_campinas.to_parquet(nome_arquivo, index=False, compression='snappy')

            print(f"[{ano}] Sucesso! {len(df_campinas)} casos de {doenca} salvos.")

            # Limpeza de memória RAM no Colab
            del df_bruto
            del df_campinas

        except Exception as e:
            print(f"[{ano}] Erro ao processar {doenca}: {e}")

print("\\nPipeline concluído! Todos os arquivos limpos e comprimidos foram salvos.")

Iniciando o Pipeline de ETL do SIEST...
\n--- Extraindo dados para: DENG ---

DENGBR14.parquet: 100%|██████████| 1.55M/1.55M [02:39<00:00, 9.72kB/s]

[2014] Sucesso! 47646 casos de DENG salvos.

DENGBR15.parquet: 100%|██████████| 3.85M/3.85M [06:38<00:00, 9.65kB/s]

[2015] Sucesso! 77190 casos de DENG salvos.

DENGBR16.parquet: 100%|██████████| 3.69M/3.69M [06:31<00:00, 9.42kB/s]

[2016] Sucesso! 10525 casos de DENG salvos.

DENGBR17.parquet: 100%|██████████| 832k/832k [01:30<00:00, 9.18kB/s]

[2017] Sucesso! 4483 casos de DENG salvos.

DENGBR18.parquet: 100%|██████████| 769k/769k [01:26<00:00, 8.88kB/s]

[2018] Sucesso! 2880 casos de DENG salvos.

DENGBR19.parquet: 100%|██████████| 3.63M/3.63M [06:35<00:00, 9.17kB/s]

[2019] Sucesso! 32170 casos de DENG salvos.

DENGBR20.parquet: 100%|██████████| 2.44M/2.44M [04:08<00:00, 9.81kB/s]

[2020] Sucesso! 9696 casos de DENG salvos.

DENGBR21.parquet: 100%|██████████| 1.65M/1.65M [03:01<00:00, 9.08kB/s]

[2021] Sucesso! 8071 casos de DENG salvos.

64655421it [00:00, 36259458607.03it/s]

[2022] Sucesso! 12446 casos de DENG salvos.

DENGBR23.parquet: 100%|██████████| 2.68M/2.68M [04:36<00:00, 9.69kB/s]

[2023] Sucesso! 12078 casos de DENG salvos.

DENGBR24.parquet: 100%|██████████| 10.7M/10.7M [18:51<00:00, 9.46kB/s]

In [ ]:
#import pandas as pd
#import os
import shutil
#from pysus.ftp.databases.sinan import SINAN

# ---------------------------------------------------------
# 1. CONFIGURAÇÕES GERAIS DO PROJETO SIEST
# ---------------------------------------------------------
sinan = SINAN().load()

IBGE_CAMPINAS = 350950
anos_analise = range(2014, 2027)
doencas = ['DENG', 'CHIK', 'ZIKA', 'LEPT', 'HEPA']

colunas_alvo = [
    'ID_MUNICIP', 'ID_UNIDADE', 'DT_NOTIFIC', 'DT_SIN_PRI',
    'NU_IDADE_N', 'CS_SEXO', 'HOSPITALIZ', 'CLASSI_FIN', 'EVOLUCAO', 'CRITERIO'
]

os.makedirs('dados_siest_parquet', exist_ok=True)

# ---------------------------------------------------------
# 2. MOTOR DE ETL COM PROCESSAMENTO EM LOTES (CHUNKING)
# ---------------------------------------------------------

print("Iniciando ETL com Processamento em Lotes (Anti-OOM)...")

for doenca in doencas:
    print(f"\n--- Extraindo dados para: {doenca} ---")

    for ano in anos_analise:
        try:
            arquivos = sinan.get_files(doenca, ano)

            if not arquivos:
                print(f"[{ano}] Sem arquivos no servidor para {doenca}.")
                continue

            # Faz o download para o cache, mas NÃO usa o .to_dataframe()!
            # Isso retorna o caminho da pasta onde o PySUS salvou os pequenos arquivos
            pasta_cache = sinan.download(arquivos)
            caminho_pasta = str(pasta_cache)

            # Lista todos os 'pedaços' (chunks) baixados
            chunks = [f for f in os.listdir(caminho_pasta) if f.endswith('.parquet')]
            lista_campinas = []

            # Lê, filtra e DESCARTA arquivo por arquivo!
            for chunk in chunks:
                caminho_arquivo = os.path.join(caminho_pasta, chunk)

                # Lê apenas um pequeno pedaço da base
                df_chunk = pd.read_parquet(caminho_arquivo)

                # Aplica o filtro de Campinas IMEDIATAMENTE
                df_chunk['ID_MUNICIP'] = pd.to_numeric(df_chunk['ID_MUNICIP'], errors='coerce')
                df_filtrado = df_chunk[df_chunk['ID_MUNICIP'] == IBGE_CAMPINAS].copy()

                if not df_filtrado.empty:
                    # Mantém apenas as colunas alvo
                    colunas_existentes = df_filtrado.columns.intersection(colunas_alvo)
                    lista_campinas.append(df_filtrado[colunas_existentes])

                # DELETA o chunk bruto gigante da memória RAM
                del df_chunk
                del df_filtrado

            # Se encontrou casos em Campinas ao longo dos chunks
            if lista_campinas:
                # Junta apenas os casos de Campinas (que cabem folgadamente na RAM)
                df_campinas_final = pd.concat(lista_campinas, ignore_index=True)

                nome_arquivo = f"dados_siest_parquet/{doenca}_campinas_{ano}.parquet"
                df_campinas_final.to_parquet(nome_arquivo, index=False, compression='snappy')

                print(f"[{ano}] Sucesso! {len(df_campinas_final)} casos salvos.")
                del df_campinas_final
            else:
                print(f"[{ano}] 0 casos registrados em Campinas para {doenca}.")

            # Limpa o HD apagando a pasta de cache do PySUS daquele ano
            shutil.rmtree(caminho_pasta, ignore_errors=True)

        except Exception as e:
            print(f"[{ano}] Erro ao processar {doenca}: {e}")

print("\nPipeline concluído com sucesso!")

Iniciando ETL com Processamento em Lotes (Anti-OOM)...

--- Extraindo dados para: DENG ---

42676892it [00:00, 6510032689.23it/s]

[2014] Sucesso! 47646 casos salvos.

109231410it [00:00, 15981224357.77it/s]

[2015] Sucesso! 77190 casos salvos.

99365364it [00:00, 15059387305.75it/s]

[2016] Sucesso! 10525 casos salvos.

22863703it [00:00, 8261312969.31it/s]

[2017] Sucesso! 4483 casos salvos.

21298476it [00:00, 8652875153.11it/s]

[2018] Sucesso! 2880 casos salvos.

110233838it [00:00, 28396648302.34it/s]

[2019] Sucesso! 32170 casos salvos.

69482617it [00:00, 14709833354.21it/s]

[2020] Sucesso! 9696 casos salvos.

42872766it [00:00, 9687087966.65it/s]

[2021] Sucesso! 8071 casos salvos.

64655421it [00:00, 24323660500.67it/s]

[2022] Sucesso! 12446 casos salvos.

61969954it [00:00, 9888937221.96it/s]

[2023] Sucesso! 12078 casos salvos.

287558389it [00:00, 18601284719.56it/s]

[2024] Sucesso! 128616 casos salvos.

DENGBR25.parquet: 100%|██████████| 2.69M/2.69M [04:53<00:00, 9.18kB/s]

[2025] Sucesso! 49600 casos salvos.

DENGBR26.parquet: 100%|██████████| 236k/236k [00:25<00:00, 9.28kB/s]

[2026] Sucesso! 2846 casos salvos.

--- Extraindo dados para: CHIK ---
[2014] Sem arquivos no servidor para CHIK.

CHIKBR15.parquet: 100%|██████████| 37.3k/37.3k [00:02<00:00, 12.5kB/s]

[2015] Sucesso! 40 casos salvos.

CHIKBR16.parquet: 100%|██████████| 222k/222k [00:18<00:00, 12.2kB/s]

[2016] Sucesso! 71 casos salvos.

CHIKBR17.parquet: 100%|██████████| 378k/378k [00:43<00:00, 8.78kB/s]

[2017] Sucesso! 195 casos salvos.

CHIKBR18.parquet: 100%|██████████| 181k/181k [00:20<00:00, 8.63kB/s]

[2018] Sucesso! 220 casos salvos.

CHIKBR19.parquet: 100%|██████████| 272k/272k [00:31<00:00, 8.62kB/s]

[2019] Sucesso! 251 casos salvos.

CHIKBR20.parquet: 100%|██████████| 156k/156k [00:19<00:00, 8.20kB/s]

[2020] Sucesso! 68 casos salvos.

CHIKBR21.parquet: 100%|██████████| 216k/216k [00:23<00:00, 9.13kB/s]

[2021] Sucesso! 66 casos salvos.

CHIKBR22.parquet: 100%|██████████| 460k/460k [00:48<00:00, 9.44kB/s]

[2022] Sucesso! 138 casos salvos.

CHIKBR23.parquet: 100%|██████████| 446k/446k [00:48<00:00, 9.29kB/s]

[2023] Sucesso! 161 casos salvos.

CHIKBR24.parquet: 100%|██████████| 714k/714k [01:15<00:00, 9.42kB/s]

[2024] Sucesso! 425 casos salvos.

CHIKBR25.parquet: 100%|██████████| 424k/424k [00:45<00:00, 9.23kB/s]

[2025] Sucesso! 1704 casos salvos.

CHIKBR26.parquet: 100%|██████████| 40.4k/40.4k [00:04<00:00, 9.63kB/s]

[2026] Sucesso! 236 casos salvos.

--- Extraindo dados para: ZIKA ---
[2014] Sem arquivos no servidor para ZIKA.
[2015] Sem arquivos no servidor para ZIKA.

ZIKABR16.parquet: 100%|██████████| 197k/197k [00:16<00:00, 11.7kB/s]

[2016] Sucesso! 705 casos salvos.

ZIKABR17.parquet:   0%|          | 0.00/22.9k [00:00<?, ?B/s]/usr/local/lib/python3.12/dist-packages/tqdm/std.py:533: TqdmWarning: clamping frac to range [0, 1]
  full_bar = Bar(frac,
ZIKABR17.parquet: 100%|██████████| 22.9k/22.9k [00:02<00:00, 9.24kB/s]

[2017] Sucesso! 132 casos salvos.

ZIKABR18.parquet: 100%|██████████| 14.4k/14.4k [00:01<00:00, 12.3kB/s]

[2018] Sucesso! 101 casos salvos.

ZIKABR19.parquet: 100%|██████████| 21.4k/21.4k [00:01<00:00, 11.3kB/s]

[2019] Sucesso! 205 casos salvos.

ZIKABR20.parquet: 100%|██████████| 14.6k/14.6k [00:01<00:00, 7.72kB/s]

[2020] Sucesso! 44 casos salvos.

ZIKABR21.parquet: 100%|██████████| 14.9k/14.9k [00:00<00:00, 15.0kB/s]

[2021] Sucesso! 14 casos salvos.

ZIKABR22.parquet: 100%|██████████| 27.9k/27.9k [00:02<00:00, 12.8kB/s]

[2022] Sucesso! 18 casos salvos.

ZIKABR23.parquet: 100%|██████████| 28.1k/28.1k [00:03<00:00, 8.47kB/s]

[2023] Sucesso! 16 casos salvos.

ZIKABR24.parquet: 100%|██████████| 33.8k/33.8k [00:02<00:00, 14.2kB/s]

[2024] Sucesso! 47 casos salvos.

ZIKABR25.parquet: 100%|██████████| 19.9k/19.9k [00:01<00:00, 14.9kB/s]

[2025] Sucesso! 36 casos salvos.

ZIKABR26.parquet:   0%|          | 0.00/947 [00:00<?, ?B/s]/usr/local/lib/python3.12/dist-packages/tqdm/std.py:533: TqdmWarning: clamping frac to range [0, 1]
  full_bar = Bar(frac,
ZIKABR26.parquet: 100%|██████████| 947/947 [00:00<00:00, 6.66kB/s]

[2026] 0 casos registrados em Campinas para ZIKA.

--- Extraindo dados para: LEPT ---

LEPTBR14.parquet: 100%|██████████| 64.6k/64.6k [00:04<00:00, 15.2kB/s]

[2014] Sucesso! 377 casos salvos.

LEPTBR15.parquet: 100%|██████████| 65.6k/65.6k [00:04<00:00, 13.8kB/s]

[2015] Sucesso! 467 casos salvos.

LEPTBR16.parquet: 100%|██████████| 50.3k/50.3k [00:02<00:00, 17.1kB/s]

[2016] Sucesso! 266 casos salvos.

LEPTBR17.parquet: 100%|██████████| 47.2k/47.2k [00:04<00:00, 11.2kB/s]

[2017] Sucesso! 199 casos salvos.

LEPTBR18.parquet: 100%|██████████| 51.6k/51.6k [00:03<00:00, 16.5kB/s]

[2018] Sucesso! 170 casos salvos.

LEPTBR19.parquet: 100%|██████████| 55.7k/55.7k [00:04<00:00, 12.8kB/s]

[2019] Sucesso! 216 casos salvos.

LEPTBR20.parquet: 100%|██████████| 33.1k/33.1k [00:01<00:00, 17.1kB/s]

[2020] Sucesso! 97 casos salvos.

LEPTBR21.parquet: 100%|██████████| 27.4k/27.4k [00:01<00:00, 17.4kB/s]

[2021] Sucesso! 107 casos salvos.

LEPTBR22.parquet: 100%|██████████| 46.6k/46.6k [00:02<00:00, 16.3kB/s]

[2022] Sucesso! 143 casos salvos.

LEPTBR23.parquet: 100%|██████████| 63.9k/63.9k [00:04<00:00, 13.8kB/s]

[2023] Sucesso! 328 casos salvos.

LEPTBR24.parquet: 100%|██████████| 84.2k/84.2k [00:04<00:00, 17.0kB/s]

[2024] Sucesso! 427 casos salvos.

LEPTBR25.parquet: 100%|██████████| 54.7k/54.7k [00:03<00:00, 16.8kB/s]

[2025] Sucesso! 420 casos salvos.

LEPTBR26.parquet: 100%|█████████▉| 564/564 [00:00<00:00, 8.98kB/s]

[2026] Sucesso! 2 casos salvos.

--- Extraindo dados para: HEPA ---

HEPABR14.parquet: 100%|██████████| 53.2k/53.2k [00:05<00:00, 9.00kB/s]

[2014] Sucesso! 712 casos salvos.

HEPABR15.parquet: 100%|██████████| 52.0k/52.0k [00:05<00:00, 9.97kB/s]

[2015] Sucesso! 713 casos salvos.

HEPABR16.parquet: 100%|██████████| 50.0k/50.0k [00:04<00:00, 11.4kB/s]

[2016] Sucesso! 759 casos salvos.

HEPABR17.parquet: 100%|██████████| 47.7k/47.7k [00:05<00:00, 8.21kB/s]

[2017] Sucesso! 455 casos salvos.

HEPABR18.parquet: 100%|██████████| 50.6k/50.6k [00:05<00:00, 8.81kB/s]

[2018] Sucesso! 490 casos salvos.

HEPABR19.parquet: 100%|██████████| 47.8k/47.8k [00:04<00:00, 10.8kB/s]

[2019] Sucesso! 267 casos salvos.

HEPABR20.parquet: 100%|██████████| 25.3k/25.3k [00:03<00:00, 6.78kB/s]

[2020] Sucesso! 139 casos salvos.

HEPABR21.parquet: 100%|██████████| 30.8k/30.8k [00:02<00:00, 10.3kB/s]

[2021] Sucesso! 270 casos salvos.

HEPABR22.parquet: 100%|██████████| 35.8k/35.8k [00:04<00:00, 7.86kB/s]

[2022] Sucesso! 265 casos salvos.

HEPABR23.parquet: 100%|██████████| 38.9k/38.9k [00:03<00:00, 10.9kB/s]

[2023] Sucesso! 417 casos salvos.
[2024] Sem arquivos no servidor para HEPA.
[2025] Sem arquivos no servidor para HEPA.
[2026] Sem arquivos no servidor para HEPA.

Pipeline concluído com sucesso!

In [ ]:
# import pandas as pd
# import os
from pysus.ftp.databases.cnes import CNES

# ---------------------------------------------------------
# 1. UNIFICAÇÃO DOS DADOS DO SINAN
# ---------------------------------------------------------
pasta_dados = 'dados_siest_parquet'
ficheiros = [os.path.join(pasta_dados, f) for f in os.listdir(pasta_dados) if f.endswith('.parquet')]

print("Consolidando todos os anos e doenças do SINAN...")
df_sinan = pd.concat([pd.read_parquet(f) for f in ficheiros], ignore_index=True)
print(f"Total de notificações consolidadas: {len(df_sinan)}")

unidades_unicas = df_sinan['ID_UNIDADE'].dropna().unique()
print(f"Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: {len(unidades_unicas)}")

# ---------------------------------------------------------
# 2. EXTRAÇÃO DE COORDENADAS (CNES)
# ---------------------------------------------------------
print("\nBaixando a base de Estabelecimentos (CNES) de São Paulo...")
cnes = CNES().load()

# CORREÇÃO AQUI: Uso de uf='SP' em vez de state='SP'
arquivos_cnes = cnes.get_files('ST', year=2026, month=2, uf='SP')
if not arquivos_cnes:
    arquivos_cnes = cnes.get_files('ST', year=2026, month=1, uf='SP')

# Arquivo de 1 mês de 1 estado é pequeno, cabe na RAM facilmente
df_cnes_sp = cnes.download(arquivos_cnes).to_dataframe()

# O CNES guarda o código do município na coluna 'CO_MUNICIP'
df_cnes_campinas = df_cnes_sp[df_cnes_sp['CO_MUNICIP'] == '350950'].copy()

# Colunas chave do CNES para a Teoria dos Grafos
colunas_cnes = ['CO_CNES', 'NO_FANTASIA', 'NU_LATITUD', 'NU_LONGIT']
colunas_existentes_cnes = df_cnes_campinas.columns.intersection(colunas_cnes)
df_cnes_campinas = df_cnes_campinas[colunas_existentes_cnes]

# Renomear para bater com a chave do SINAN
df_cnes_campinas.rename(columns={'CO_CNES': 'ID_UNIDADE'}, inplace=True)

# ---------------------------------------------------------
# 3. O CRUZAMENTO ESPACIAL (MERGE)
# ---------------------------------------------------------
print("\nRealizando o cruzamento geoespacial...")

# Limpeza e equalização das chaves para o Join perfeito
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].replace('nan', pd.NA) # Retorna os nulos ao estado real

df_cnes_campinas['ID_UNIDADE'] = df_cnes_campinas['ID_UNIDADE'].astype(str)

# Left Join: Mantém todos os casos e traz as coordenadas quando os códigos baterem
df_siest_geo = pd.merge(df_sinan, df_cnes_campinas, on='ID_UNIDADE', how='left')

# ---------------------------------------------------------
# 4. CARGA DO ARQUIVO MESTRE
# ---------------------------------------------------------
ficheiro_final = 'dados_siest_parquet/siest_casos_geolocalizados.parquet'
df_siest_geo.to_parquet(ficheiro_final, index=False, compression='snappy')

print(f"\nSucesso! O arquivo mestre geolocalizado foi salvo em: {ficheiro_final}")

# Opcional: mostrar uma prévia dos dados para você validar
print("\nPrévia dos primeiros casos com coordenadas:")
print(df_siest_geo[['DT_NOTIFIC', 'ID_UNIDADE', 'NO_FANTASIA', 'NU_LATITUD', 'NU_LONGIT']].dropna().head())

Consolidando todos os anos e doenças do SINAN...
Total de notificações consolidadas: 410846
Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: 338

Baixando a base de Estabelecimentos (CNES) de São Paulo...

STSP2602.parquet: 100%|██████████| 277k/277k [00:38<00:00, 7.12kB/s]

KeyError: 'CO_MUNICIP'

In [ ]:
# import pandas as pd
# import os
from pysus.ftp.databases.cnes import CNES

# ---------------------------------------------------------
# 1. UNIFICAÇÃO DOS DADOS DO SINAN
# ---------------------------------------------------------
pasta_dados = 'dados_siest_parquet'
ficheiros = [os.path.join(pasta_dados, f) for f in os.listdir(pasta_dados) if f.endswith('.parquet')]

print("Consolidando todos os anos e doenças do SINAN...")
df_sinan = pd.concat([pd.read_parquet(f) for f in ficheiros], ignore_index=True)
print(f"Total de notificações consolidadas: {len(df_sinan)}")

unidades_unicas = df_sinan['ID_UNIDADE'].dropna().unique()
print(f"Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: {len(unidades_unicas)}")

# ---------------------------------------------------------
# 2. EXTRAÇÃO DE COORDENADAS (CNES)
# ---------------------------------------------------------
print("\nBaixando a base de Estabelecimentos (CNES) de São Paulo...")
cnes = CNES().load()

arquivos_cnes = cnes.get_files('ST', year=2026, month=2, uf='SP')
if not arquivos_cnes:
    arquivos_cnes = cnes.get_files('ST', year=2026, month=1, uf='SP')

# Arquivo de 1 mês de 1 estado cabe na RAM facilmente
df_cnes_sp = cnes.download(arquivos_cnes).to_dataframe()

# Busca dinâmica pela coluna de Município no CNES (Geralmente é CO_DUFMUN)
coluna_municipio = 'CO_DUFMUN' if 'CO_DUFMUN' in df_cnes_sp.columns else 'CO_MUNICIP'

# Se o DataSUS tiver mudado a sigla novamente, o código avisa:
if coluna_municipio not in df_cnes_sp.columns:
    possiveis_colunas = [col for col in df_cnes_sp.columns if 'MUN' in col]
    print(f"Colunas de município encontradas: {possiveis_colunas}")
    coluna_municipio = possiveis_colunas[0] # Usa a primeira encontrada

# Filtra apenas os estabelecimentos de Campinas (código 350950)
df_cnes_campinas = df_cnes_sp[df_cnes_sp[coluna_municipio] == '350950'].copy()

# Colunas chave do CNES para a Teoria dos Grafos
colunas_cnes = ['CO_CNES', 'NO_FANTASIA', 'NU_LATITUD', 'NU_LONGIT']
colunas_existentes_cnes = df_cnes_campinas.columns.intersection(colunas_cnes)
df_cnes_campinas = df_cnes_campinas[colunas_existentes_cnes]

# Renomear para bater com a chave do SINAN
if 'CO_CNES' in df_cnes_campinas.columns:
    df_cnes_campinas.rename(columns={'CO_CNES': 'ID_UNIDADE'}, inplace=True)

# ---------------------------------------------------------
# 3. O CRUZAMENTO ESPACIAL (MERGE)
# ---------------------------------------------------------
print("\nRealizando o cruzamento geoespacial...")

# Limpeza e equalização das chaves para o Join perfeito
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].replace('nan', pd.NA)

df_cnes_campinas['ID_UNIDADE'] = df_cnes_campinas['ID_UNIDADE'].astype(str)

# Left Join: Mantém todos os casos e traz as coordenadas quando os códigos baterem
df_siest_geo = pd.merge(df_sinan, df_cnes_campinas, on='ID_UNIDADE', how='left')

# ---------------------------------------------------------
# 4. CARGA DO ARQUIVO MESTRE
# ---------------------------------------------------------
ficheiro_final = 'dados_siest_parquet/siest_casos_geolocalizados.parquet'
df_siest_geo.to_parquet(ficheiro_final, index=False, compression='snappy')

print(f"\nSucesso! O arquivo mestre geolocalizado foi salvo em: {ficheiro_final}")

# Opcional: mostrar uma prévia dos dados para validar
print("\nPrévia dos primeiros casos com coordenadas:")
colunas_previa = [c for c in ['DT_NOTIFIC', 'ID_UNIDADE', 'NO_FANTASIA', 'NU_LATITUD', 'NU_LONGIT'] if c in df_siest_geo.columns]
print(df_siest_geo[colunas_previa].dropna().head())

Consolidando todos os anos e doenças do SINAN...
Total de notificações consolidadas: 410846
Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: 338

Baixando a base de Estabelecimentos (CNES) de São Paulo...

0it [00:00, ?it/s]

AttributeError: 'list' object has no attribute 'to_dataframe'

In [ ]:
# import pandas as pd
# import os
from pysus.ftp.databases.cnes import CNES

# ---------------------------------------------------------
# 1. UNIFICAÇÃO DOS DADOS DO SINAN
# ---------------------------------------------------------
pasta_dados = 'dados_siest_parquet'
ficheiros = [os.path.join(pasta_dados, f) for f in os.listdir(pasta_dados) if f.endswith('.parquet')]

print("Consolidando todos os anos e doenças do SINAN...")
df_sinan = pd.concat([pd.read_parquet(f) for f in ficheiros], ignore_index=True)
print(f"Total de notificações consolidadas: {len(df_sinan)}")

unidades_unicas = df_sinan['ID_UNIDADE'].dropna().unique()
print(f"Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: {len(unidades_unicas)}")

# ---------------------------------------------------------
# 2. EXTRAÇÃO DE COORDENADAS (CNES)
# ---------------------------------------------------------
print("\nBaixando a base de Estabelecimentos (CNES) de São Paulo...")
cnes = CNES().load()

arquivos_cnes = cnes.get_files('ST', year=2026, month=2, uf='SP')
if not arquivos_cnes:
    arquivos_cnes = cnes.get_files('ST', year=2026, month=1, uf='SP')

# O download do CNES retorna uma lista de caminhos de arquivos salvos
caminhos_cnes = cnes.download(arquivos_cnes)

# Lemos todos os arquivos da lista e transformamos em um único DataFrame do Pandas
if isinstance(caminhos_cnes, list):
    df_cnes_sp = pd.concat([pd.read_parquet(f) for f in caminhos_cnes], ignore_index=True)
else:
    df_cnes_sp = caminhos_cnes.to_dataframe() # Prevenção caso a versão do PySUS mude

# Busca dinâmica pela coluna de Município no CNES (Geralmente é CO_DUFMUN)
coluna_municipio = 'CO_DUFMUN' if 'CO_DUFMUN' in df_cnes_sp.columns else 'CO_MUNICIP'

# Se o DataSUS tiver mudado a sigla novamente, o código avisa:
if coluna_municipio not in df_cnes_sp.columns:
    possiveis_colunas = [col for col in df_cnes_sp.columns if 'MUN' in col]
    print(f"Colunas de município encontradas: {possiveis_colunas}")
    coluna_municipio = possiveis_colunas[0] # Usa a primeira encontrada

# Filtra apenas os estabelecimentos de Campinas (código 350950)
df_cnes_campinas = df_cnes_sp[df_cnes_sp[coluna_municipio] == '350950'].copy()

# Colunas chave do CNES para a Teoria dos Grafos
colunas_cnes = ['CO_CNES', 'NO_FANTASIA', 'NU_LATITUD', 'NU_LONGIT']
colunas_existentes_cnes = df_cnes_campinas.columns.intersection(colunas_cnes)
df_cnes_campinas = df_cnes_campinas[colunas_existentes_cnes]

# Renomear para bater com a chave do SINAN
if 'CO_CNES' in df_cnes_campinas.columns:
    df_cnes_campinas.rename(columns={'CO_CNES': 'ID_UNIDADE'}, inplace=True)

# ---------------------------------------------------------
# 3. O CRUZAMENTO ESPACIAL (MERGE)
# ---------------------------------------------------------
print("\nRealizando o cruzamento geoespacial...")

# Limpeza e equalização das chaves para o Join perfeito
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].replace('nan', pd.NA)

df_cnes_campinas['ID_UNIDADE'] = df_cnes_campinas['ID_UNIDADE'].astype(str)

# Left Join: Mantém todos os casos e traz as coordenadas quando os códigos baterem
df_siest_geo = pd.merge(df_sinan, df_cnes_campinas, on='ID_UNIDADE', how='left')

# ---------------------------------------------------------
# 4. CARGA DO ARQUIVO MESTRE
# ---------------------------------------------------------
ficheiro_final = 'dados_siest_parquet/siest_casos_geolocalizados.parquet'
df_siest_geo.to_parquet(ficheiro_final, index=False, compression='snappy')

print(f"\nSucesso! O arquivo mestre geolocalizado foi salvo em: {ficheiro_final}")

# Opcional: mostrar uma prévia dos dados para validar
print("\nPrévia dos primeiros casos com coordenadas:")
colunas_previa = [c for c in ['DT_NOTIFIC', 'ID_UNIDADE', 'NO_FANTASIA', 'NU_LATITUD', 'NU_LONGIT'] if c in df_siest_geo.columns]
print(df_siest_geo[colunas_previa].dropna().head())

Consolidando todos os anos e doenças do SINAN...
Total de notificações consolidadas: 410846
Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: 338

Baixando a base de Estabelecimentos (CNES) de São Paulo...

0it [00:00, ?it/s]

ValueError: No objects to concatenate

In [ ]:
from pysus.ftp.databases.cnes import CNES

print("Iniciando Diagnóstico do CNES...")
cnes = CNES().load()

# Puxa apenas um mês de amostra
arquivos_cnes = cnes.get_files('ST', year=2024, month=1, uf='SP')
caminhos = cnes.download(arquivos_cnes)

# Tratamento defensivo para o tipo de retorno
if isinstance(caminhos, list):
    df_amostra = pd.read_parquet(caminhos[0])
else:
    df_amostra = caminhos.to_dataframe()

print("\n--- RELATÓRIO DE DIAGNÓSTICO ---")
print(f"Total de linhas na amostra: {len(df_amostra)}")

# Procura colunas relacionadas a Município
colunas_mun = [col for col in df_amostra.columns if 'MUN' in col]
print(f"\n1. Colunas que contêm 'MUN' (Município): {colunas_mun}")

# Procura colunas relacionadas ao Código CNES (ID_UNIDADE)
colunas_cnes = [col for col in df_amostra.columns if 'CNES' in col]
print(f"2. Colunas que contêm 'CNES': {colunas_cnes}")

# Procura colunas relacionadas à Latitude/Longitude
colunas_geo = [col for col in df_amostra.columns if 'LAT' in col or 'LONG' in col]
print(f"3. Colunas Geográficas: {colunas_geo}")

print("\n4. Tipos de dados das primeiras 10 colunas:")
print(df_amostra.dtypes.head(10))

Iniciando Diagnóstico do CNES...

0it [00:00, ?it/s]

IndexError: list index out of range

In [ ]:
from pysus.ftp.databases.cnes import CNES

# ---------------------------------------------------------
# 1. UNIFICAÇÃO DOS DADOS DO SINAN
# ---------------------------------------------------------
pasta_dados = 'dados_siest_parquet'
ficheiros = [os.path.join(pasta_dados, f) for f in os.listdir(pasta_dados) if f.endswith('.parquet')]

print("Consolidando todos os anos e doenças do SINAN...")
df_sinan = pd.concat([pd.read_parquet(f) for f in ficheiros], ignore_index=True)
print(f"Total de notificações consolidadas: {len(df_sinan)}")

unidades_unicas = df_sinan['ID_UNIDADE'].dropna().unique()
print(f"Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: {len(unidades_unicas)}")

# # ---------------------------------------------------------
# 2. EXTRAÇÃO DE COORDENADAS (CNES)
# ---------------------------------------------------------
print("\nBaixando a base de Estabelecimentos (CNES) de São Paulo (2026)...")
cnes = CNES().load()

# Usamos as datas que sabemos que estão ativas no FTP do DataSUS
arquivos_cnes = cnes.get_files('ST', year=2026, month=2, uf='SP')
if not arquivos_cnes:
    arquivos_cnes = cnes.get_files('ST', year=2026, month=1, uf='SP')

caminhos_cnes = cnes.download(arquivos_cnes)

# Leitura segura da lista de arquivos
if isinstance(caminhos_cnes, list) and len(caminhos_cnes) > 0:
    df_cnes_sp = pd.concat([pd.read_parquet(f) for f in caminhos_cnes], ignore_index=True)
else:
    df_cnes_sp = caminhos_cnes.to_dataframe()

# --- PROGRAMAÇÃO DEFENSIVA: BUSCA DINÂMICA DE COLUNAS ---

# 1. Encontrar coluna de Município
coluna_municipio = None
for col in ['CO_DUFMUN', 'CO_MUNICIP', 'CO_MUNICIPIO', 'MUNICIPIO']:
    if col in df_cnes_sp.columns:
        coluna_municipio = col
        break

# 2. Encontrar coluna CNES (ID_UNIDADE)
coluna_cnes = 'CO_CNES' if 'CO_CNES' in df_cnes_sp.columns else 'CNES'

# 3. Encontrar colunas Geográficas
coluna_lat = 'NU_LATITUD' if 'NU_LATITUD' in df_cnes_sp.columns else 'LATITUDE'
coluna_lon = 'NU_LONGIT' if 'NU_LONGIT' in df_cnes_sp.columns else 'LONGITUDE'

print(f"Mapeamento Automático -> Município: {coluna_municipio} | CNES: {coluna_cnes}")

# Filtra apenas os estabelecimentos de Campinas (código 350950)
df_cnes_sp[coluna_municipio] = df_cnes_sp[coluna_municipio].astype(str)
df_cnes_campinas = df_cnes_sp[df_cnes_sp[coluna_municipio] == '350950'].copy()

# Mantém apenas as colunas essenciais
colunas_interesse_cnes = [coluna_cnes, 'NO_FANTASIA', coluna_lat, coluna_lon]
colunas_existentes = [c for c in colunas_interesse_cnes if c in df_cnes_campinas.columns]
df_cnes_campinas = df_cnes_campinas[colunas_existentes]

# Padroniza os nomes para o Merge e para o MongoDB
df_cnes_campinas.rename(columns={
    coluna_cnes: 'ID_UNIDADE',
    coluna_lat: 'LATITUDE',
    coluna_lon: 'LONGITUDE'
}, inplace=True)


# ---------------------------------------------------------
# 3. O CRUZAMENTO ESPACIAL (MERGE)
# ---------------------------------------------------------
print("\nRealizando o cruzamento geoespacial...")

# Limpeza profunda (Type Casting) para garantir que o cruzamento bata
# Remove '.0' de números lidos como decimais e converte tudo para texto puro
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].replace('nan', pd.NA)

df_cnes_campinas['ID_UNIDADE'] = df_cnes_campinas['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)

# Left Join: Cruza os 410 mil casos com os seus respectivos hospitais
df_siest_geo = pd.merge(df_sinan, df_cnes_campinas, on='ID_UNIDADE', how='left')


# ---------------------------------------------------------
# 4. CARGA DO ARQUIVO MESTRE
# ---------------------------------------------------------
ficheiro_final = 'dados_siest_parquet/siest_casos_geolocalizados.parquet'
df_siest_geo.to_parquet(ficheiro_final, index=False, compression='snappy')

print(f"\n✅ SUCESSO ABSOLUTO! O arquivo mestre geolocalizado foi salvo em: {ficheiro_final}")

# Mostra uma amostra validando as coordenadas
print("\nPrévia de 5 casos consolidados com Latitude e Longitude:")
colunas_previa = ['DT_NOTIFIC', 'ID_UNIDADE', 'NO_FANTASIA', 'LATITUDE', 'LONGITUDE']
colunas_previa_existentes = [c for c in colunas_previa if c in df_siest_geo.columns]
print(df_siest_geo[colunas_previa_existentes].dropna().head())

Consolidando todos os anos e doenças do SINAN...
Total de notificações consolidadas: 410846
Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: 338

Baixando a base de Estabelecimentos (CNES) de São Paulo (2026)...

0it [00:00, ?it/s]

AttributeError: 'list' object has no attribute 'to_dataframe'

In [ ]:
from pysus.ftp.databases.cnes import CNES

# ---------------------------------------------------------
# 1. UNIFICAÇÃO DOS DADOS DO SINAN
# ---------------------------------------------------------
pasta_dados = 'dados_siest_parquet'
ficheiros = [os.path.join(pasta_dados, f) for f in os.listdir(pasta_dados) if f.endswith('.parquet')]

print("Consolidando todos os anos e doenças do SINAN...")
df_sinan = pd.concat([pd.read_parquet(f) for f in ficheiros], ignore_index=True)
print(f"Total de notificações consolidadas: {len(df_sinan)}")

unidades_unicas = df_sinan['ID_UNIDADE'].dropna().unique()
print(f"Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: {len(unidades_unicas)}")

# ---------------------------------------------------------
# 2. EXTRAÇÃO DE COORDENADAS (CNES)
# ---------------------------------------------------------
print("\nBaixando a base de Estabelecimentos (CNES) de São Paulo...")
cnes = CNES().load()

# O DataSUS pode não ter fechado 2026. Vamos puxar Dezembro de 2025 para garantir dados sólidos.
arquivos_cnes = cnes.get_files('ST', year=2025, month=12, uf='SP')
if not arquivos_cnes:
    arquivos_cnes = cnes.get_files('ST', year=2024, month=1, uf='SP')

objetos_cnes = cnes.download(arquivos_cnes)

# A grande sacada descoberta no seu arquivo: cada objeto da lista tem o .to_dataframe()
if isinstance(objetos_cnes, list):
    if len(objetos_cnes) == 0:
        raise ValueError("O DataSUS não retornou nenhum arquivo CNES. Verifique o ano/mês.")
    df_cnes_sp = pd.concat([obj.to_dataframe() for obj in objetos_cnes], ignore_index=True)
else:
    df_cnes_sp = objetos_cnes.to_dataframe()

# --- PROGRAMAÇÃO DEFENSIVA: BUSCA DINÂMICA DE COLUNAS ---
# O comando next() procura a primeira opção válida na lista de possíveis nomes do DataSUS
coluna_municipio = next((col for col in ['CODUFMUN', 'CO_DUFMUN', 'CO_MUNICIP', 'CO_MUNICIPIO'] if col in df_cnes_sp.columns), None)
coluna_cnes = next((col for col in ['CNES', 'CO_CNES'] if col in df_cnes_sp.columns), None)
coluna_lat = next((col for col in ['LATITUDE', 'NU_LATITUD'] if col in df_cnes_sp.columns), None)
coluna_lon = next((col for col in ['LONGITUDE', 'NU_LONGIT'] if col in df_cnes_sp.columns), None)

print(f"Mapeamento CNES -> Município: {coluna_municipio} | CNES: {coluna_cnes} | Lat: {coluna_lat} | Lon: {coluna_lon}")

# Filtra apenas os estabelecimentos de Campinas (código 350950)
df_cnes_sp[coluna_municipio] = df_cnes_sp[coluna_municipio].astype(str)
df_cnes_campinas = df_cnes_sp[df_cnes_sp[coluna_municipio] == '350950'].copy()

# Mantém apenas as colunas essenciais para o grafo
colunas_interesse_cnes = [coluna_cnes, 'NO_FANTASIA', coluna_lat, coluna_lon]
colunas_existentes = [c for c in colunas_interesse_cnes if c and c in df_cnes_campinas.columns]
df_cnes_campinas = df_cnes_campinas[colunas_existentes]

# Padroniza os nomes para o Merge
df_cnes_campinas.rename(columns={
    coluna_cnes: 'ID_UNIDADE',
    coluna_lat: 'LATITUDE',
    coluna_lon: 'LONGITUDE'
}, inplace=True)


# ---------------------------------------------------------
# 3. O CRUZAMENTO ESPACIAL (MERGE)
# ---------------------------------------------------------
print("\nRealizando o cruzamento geoespacial...")

# Limpeza e conversão para string para o Join funcionar sem falhas
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].replace('nan', pd.NA)

df_cnes_campinas['ID_UNIDADE'] = df_cnes_campinas['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)

# Left Join: Anexa as coordenadas aos 410 mil casos do SINAN
df_siest_geo = pd.merge(df_sinan, df_cnes_campinas, on='ID_UNIDADE', how='left')

# ---------------------------------------------------------
# 4. CARGA DO ARQUIVO MESTRE
# ---------------------------------------------------------
ficheiro_final = 'dados_siest_parquet/siest_casos_geolocalizados.parquet'
df_siest_geo.to_parquet(ficheiro_final, index=False, compression='snappy')

print(f"\n✅ SUCESSO ABSOLUTO! O arquivo mestre geolocalizado foi salvo em: {ficheiro_final}")

# Mostra uma amostra validando as coordenadas
print("\nPrévia de 5 casos consolidados com Latitude e Longitude:")
colunas_previa = ['DT_NOTIFIC', 'ID_UNIDADE', 'NO_FANTASIA', 'LATITUDE', 'LONGITUDE']
colunas_previa_existentes = [c for c in colunas_previa if c in df_siest_geo.columns]
print(df_siest_geo[colunas_previa_existentes].dropna().head())

Consolidando todos os anos e doenças do SINAN...
Total de notificações consolidadas: 410846
Total de Nós (Unidades de Saúde) únicas do SINAN a mapear: 338

Baixando a base de Estabelecimentos (CNES) de São Paulo...

0it [00:00, ?it/s]

ValueError: O DataSUS não retornou nenhum arquivo CNES. Verifique o ano/mês.

In [ ]:
# ---------------------------------------------------------
# 2. EXTRAÇÃO DE COORDENADAS (CNES)
# ---------------------------------------------------------
print("\nBaixando a base de Estabelecimentos (CNES) de São Paulo...")
cnes = CNES().load()

# O DataSUS apaga arquivos antigos do CNES. Precisamos usar o mês mais recente.
# Sabemos que 2026 e mês 2 funciona perfeitamente no seu ambiente.
arquivos_cnes = cnes.get_files('ST', year=2026, month=2, uf='SP')
if not arquivos_cnes:
    arquivos_cnes = cnes.get_files('ST', year=2026, month=1, uf='SP')

objetos_cnes = cnes.download(arquivos_cnes)

if isinstance(objetos_cnes, list):
    if len(objetos_cnes) == 0:
        raise ValueError("O DataSUS não retornou nenhum arquivo CNES. Verifique o ano/mês.")
    # O PySUS retorna uma lista de objetos que possuem o método .to_dataframe()
    df_cnes_sp = pd.concat([obj.to_dataframe() for obj in objetos_cnes], ignore_index=True)
else:
    df_cnes_sp = objetos_cnes.to_dataframe()

# --- PROGRAMAÇÃO DEFENSIVA: BUSCA DINÂMICA DE COLUNAS ---
coluna_municipio = next((col for col in ['CODUFMUN', 'CO_DUFMUN', 'CO_MUNICIP', 'CO_MUNICIPIO'] if col in df_cnes_sp.columns), None)
coluna_cnes = next((col for col in ['CNES', 'CO_CNES'] if col in df_cnes_sp.columns), None)
coluna_lat = next((col for col in ['LATITUDE', 'NU_LATITUD'] if col in df_cnes_sp.columns), None)
coluna_lon = next((col for col in ['LONGITUDE', 'NU_LONGIT'] if col in df_cnes_sp.columns), None)

print(f"Mapeamento CNES -> Município: {coluna_municipio} | CNES: {coluna_cnes} | Lat: {coluna_lat} | Lon: {coluna_lon}")

# Filtra apenas os estabelecimentos de Campinas (código 350950)
df_cnes_sp[coluna_municipio] = df_cnes_sp[coluna_municipio].astype(str)
df_cnes_campinas = df_cnes_sp[df_cnes_sp[coluna_municipio] == '350950'].copy()

# Mantém apenas as colunas essenciais para o grafo
colunas_interesse_cnes = [coluna_cnes, 'NO_FANTASIA', coluna_lat, coluna_lon]
colunas_existentes = [c for c in colunas_interesse_cnes if c and c in df_cnes_campinas.columns]
df_cnes_campinas = df_cnes_campinas[colunas_existentes]

# Padroniza os nomes para o Merge
df_cnes_campinas.rename(columns={
    coluna_cnes: 'ID_UNIDADE',
    coluna_lat: 'LATITUDE',
    coluna_lon: 'LONGITUDE'
}, inplace=True)


# ---------------------------------------------------------
# 3. O CRUZAMENTO ESPACIAL (MERGE)
# ---------------------------------------------------------
print("\nRealizando o cruzamento geoespacial...")

df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].replace('nan', pd.NA)

df_cnes_campinas['ID_UNIDADE'] = df_cnes_campinas['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)

df_siest_geo = pd.merge(df_sinan, df_cnes_campinas, on='ID_UNIDADE', how='left')

# ---------------------------------------------------------
# 4. CARGA DO ARQUIVO MESTRE
# ---------------------------------------------------------
ficheiro_final = 'dados_siest_parquet/siest_casos_geolocalizados.parquet'
df_siest_geo.to_parquet(ficheiro_final, index=False, compression='snappy')

print(f"\n✅ SUCESSO ABSOLUTO! O arquivo mestre geolocalizado foi salvo em: {ficheiro_final}")

print("\nPrévia de 5 casos consolidados com Latitude e Longitude:")
colunas_previa = ['DT_NOTIFIC', 'ID_UNIDADE', 'NO_FANTASIA', 'LATITUDE', 'LONGITUDE']
colunas_previa_existentes = [c for c in colunas_previa if c in df_siest_geo.columns]
print(df_siest_geo[colunas_previa_existentes].dropna().head())

Baixando a base de Estabelecimentos (CNES) de São Paulo...

0it [00:00, ?it/s]

ValueError: O DataSUS não retornou nenhum arquivo CNES. Verifique o ano/mês.

In [ ]:
# ---------------------------------------------------------
# 2. EXTRAÇÃO DE COORDENADAS (CNES) COM BUSCADOR DINÂMICO
# ---------------------------------------------------------
print("\nBaixando a base de Estabelecimentos (CNES) de São Paulo...")
cnes = CNES().load()

arquivos_cnes = []

# Crawler Dinâmico: Vasculha do início de 2026 para trás até encontrar um arquivo no FTP
for ano_busca in [2026, 2025, 2024]:
    for mes_busca in range(12, 0, -1):
        # Como estamos no início de 2026, ignora meses futuros
        if ano_busca == 2026 and mes_busca > 3:
            continue

        print(f"Buscando CNES de {ano_busca}/{mes_busca:02d}...", end=" ")
        arquivos_cnes = cnes.get_files('ST', year=ano_busca, month=mes_busca, uf='SP')

        if arquivos_cnes:
            print("Encontrado!")
            break
        else:
            print("Vazio no servidor.")

    if arquivos_cnes:
        break

if not arquivos_cnes:
    raise ValueError("Falha crítica: O FTP do DataSUS não retornou arquivos recentes.")

objetos_cnes = cnes.download(arquivos_cnes)

# Conversão para DataFrame (Garante o funcionamento baseado no retorno do PySUS)
if isinstance(objetos_cnes, list):
    df_cnes_sp = pd.concat([obj.to_dataframe() for obj in objetos_cnes], ignore_index=True)
else:
    df_cnes_sp = objetos_cnes.to_dataframe()

# --- PROGRAMAÇÃO DEFENSIVA: BUSCA DINÂMICA DE COLUNAS ---
coluna_municipio = next((col for col in ['CODUFMUN', 'CO_DUFMUN', 'CO_MUNICIP', 'CO_MUNICIPIO'] if col in df_cnes_sp.columns), None)
coluna_cnes = next((col for col in ['CNES', 'CO_CNES'] if col in df_cnes_sp.columns), None)
coluna_lat = next((col for col in ['LATITUDE', 'NU_LATITUD'] if col in df_cnes_sp.columns), None)
coluna_lon = next((col for col in ['LONGITUDE', 'NU_LONGIT'] if col in df_cnes_sp.columns), None)

print(f"\nMapeamento CNES -> Município: {coluna_municipio} | CNES: {coluna_cnes} | Lat: {coluna_lat} | Lon: {coluna_lon}")

# Filtra apenas os estabelecimentos de Campinas (código 350950)
df_cnes_sp[coluna_municipio] = df_cnes_sp[coluna_municipio].astype(str)
df_cnes_campinas = df_cnes_sp[df_cnes_sp[coluna_municipio] == '350950'].copy()

# Mantém apenas as colunas essenciais para o grafo
colunas_interesse_cnes = [coluna_cnes, 'NO_FANTASIA', coluna_lat, coluna_lon]
colunas_existentes = [c for c in colunas_interesse_cnes if c and c in df_cnes_campinas.columns]
df_cnes_campinas = df_cnes_campinas[colunas_existentes]

# Padroniza os nomes para o Merge
df_cnes_campinas.rename(columns={
    coluna_cnes: 'ID_UNIDADE',
    coluna_lat: 'LATITUDE',
    coluna_lon: 'LONGITUDE'
}, inplace=True)


# ---------------------------------------------------------
# 3. O CRUZAMENTO ESPACIAL (MERGE)
# ---------------------------------------------------------
print("\nRealizando o cruzamento geoespacial...")

df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)
df_sinan['ID_UNIDADE'] = df_sinan['ID_UNIDADE'].replace('nan', pd.NA)

df_cnes_campinas['ID_UNIDADE'] = df_cnes_campinas['ID_UNIDADE'].astype(str).str.replace(r'\.0$', '', regex=True)

df_siest_geo = pd.merge(df_sinan, df_cnes_campinas, on='ID_UNIDADE', how='left')

# ---------------------------------------------------------
# 4. CARGA DO ARQUIVO MESTRE
# ---------------------------------------------------------
ficheiro_final = 'dados_siest_parquet/siest_casos_geolocalizados.parquet'
df_siest_geo.to_parquet(ficheiro_final, index=False, compression='snappy')

print(f"\n✅ SUCESSO ABSOLUTO! O arquivo mestre geolocalizado foi salvo em: {ficheiro_final}")

print("\nPrévia de 5 casos consolidados com Latitude e Longitude:")
colunas_previa = ['DT_NOTIFIC', 'ID_UNIDADE', 'NO_FANTASIA', 'LATITUDE', 'LONGITUDE']
colunas_previa_existentes = [c for c in colunas_previa if c in df_siest_geo.columns]
print(df_siest_geo[colunas_previa_existentes].dropna().head())

Baixando a base de Estabelecimentos (CNES) de São Paulo...
Buscando CNES de 2026/03... Vazio no servidor.
Buscando CNES de 2026/02... Vazio no servidor.
Buscando CNES de 2026/01... Vazio no servidor.
Buscando CNES de 2025/12... Vazio no servidor.
Buscando CNES de 2025/11... Vazio no servidor.
Buscando CNES de 2025/10... Vazio no servidor.
Buscando CNES de 2025/09... Vazio no servidor.
Buscando CNES de 2025/08... Vazio no servidor.
Buscando CNES de 2025/07... Vazio no servidor.
Buscando CNES de 2025/06... Vazio no servidor.
Buscando CNES de 2025/05... Vazio no servidor.
Buscando CNES de 2025/04... Vazio no servidor.
Buscando CNES de 2025/03... Vazio no servidor.
Buscando CNES de 2025/02... Vazio no servidor.
Buscando CNES de 2025/01... Vazio no servidor.
Buscando CNES de 2024/12... Vazio no servidor.
Buscando CNES de 2024/11... Vazio no servidor.
Buscando CNES de 2024/10... Vazio no servidor.
Buscando CNES de 2024/09... Vazio no servidor.
Buscando CNES de 2024/08... Vazio no servidor.
Buscando CNES de 2024/07... Vazio no servidor.
Buscando CNES de 2024/06... Vazio no servidor.
Buscando CNES de 2024/05... Vazio no servidor.
Buscando CNES de 2024/04... Vazio no servidor.
Buscando CNES de 2024/03... Vazio no servidor.
Buscando CNES de 2024/02... Vazio no servidor.
Buscando CNES de 2024/01... Vazio no servidor.

ValueError: Falha crítica: O FTP do DataSUS não retornou arquivos recentes.

In [ ]:
import pandas as pd
import os
import matplotlib.pyplot as plt

# ---------------------------------------------------------
# 1. CARREGAMENTO SEGURO DOS DADOS LOCAIS
# ---------------------------------------------------------
print("Carregando o tesouro de dados do SINAN...")

pasta_dados = 'dados_siest_parquet'
ficheiros = [os.path.join(pasta_dados, f) for f in os.listdir(pasta_dados) if f.endswith('.parquet')]

# Lendo e consolidando tudo
df_sinan = pd.concat([pd.read_parquet(f) for f in ficheiros], ignore_index=True)
print(f"Total de registros carregados: {len(df_sinan)}")


print(df_sinan)

Carregando o tesouro de dados do SINAN...
Total de registros carregados: 410846
       DT_NOTIFIC  ID_MUNICIP ID_UNIDADE DT_SIN_PRI NU_IDADE_N CS_SEXO  \
0        20150128      350950    2039656   20150126       4026       M
1        20150219      350950    2046318   20150215       4018       F
2        20150216      350950    2039656   20150216       4042       F
3        20150224      350950    2081938   20150218       4051       I
4        20150223      350950    2022664   20150220       4062       F
...           ...         ...        ...        ...        ...     ...
410841   20211103      350950    2023164   20211027       4040       M
410842   20211111      350950    2082128   20211106       4039       F
410843   20211124      350950    2036398   20211122       4024       F
410844   20211206      350950    2046318   20211129       4038       F
410845   20210531      350950    6032338   20210531       4050       M

       HOSPITALIZ CLASSI_FIN CRITERIO EVOLUCAO
0                         10        2        1
1                         10        1        1
2               2         10        2        1
3                         10        1        1
4               2         10        2        1
...           ...        ...      ...      ...
410841          2         5         2        1
410842          1         5         1        1
410843                    5         2        1
410844          2         5         1        1
410845                    5         1        1

[410846 rows x 10 columns]